# Generated by Django 5.0.6 on 2024-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the praducts')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'All Brand',
            },
        ),
        migrations.CreateModel(
            name='Praducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the praducts')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of the praducts')),
                ('price', models.IntegerField(verbose_name='Price of the praducts')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('brand', models.ManyToManyField(max_length=255, related_name='product_brand', to='product.brand')),
            ],
            options={
                'verbose_name': 'Praducts',
                'verbose_name_plural': 'All Praducts',
            },
        ),
    ]
