# Generated by Django 5.0.6 on 2024-07-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the blog cart')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of the blog cart')),
                ('description', models.TextField(verbose_name='Text of the blog cart')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the praducts')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'blog Brand',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Comment name')),
                ('email', models.EmailField(max_length=254, verbose_name='Comment email')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oment_of_th_blog', to='blog.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
